### ISSUE TITLE
用的Home Assistant 2023.8.1的版本，步骤都按着来的，卡片页面不显示价格以及提示

### ISSUE THREAD

**Issue by lucienyida** [cheny95/olipirce#4]
![微信图片_20230809142415](https://github.com/cheny95/olipirce/assets/96853173/e255d0f5-1d63-4e9c-85db-3b1374977454)

**Comment by cheny95** [comment]
请检查网络或配置，或更换其他地区测试下？我这边是ok的。
<img width="388" alt="image" src="https://github.com/cheny95/olipirce/assets/6293952/45137002-cc78-48ac-9e9b-2f4132c1d58f">
<img width="411" alt="image" src="https://github.com/cheny95/olipirce/assets/6293952/f00323aa-1bf4-4c39-9ca4-16727dbfa0e9">
<img width="282" alt="image" src="https://github.com/cheny95/olipirce/assets/6293952/508e1ecc-c2fd-4c95-ae32-347ac96db92b">
